{'application': False,
 'author': 'Snifx Studio',
 'category': 'Human Resources/Time Off',
 'data': ['security/hr_employee_pic_access.xml',
          'data/mail_template.xml',
          'views/hr_leave_views.xml'],
 'depends': ['hr_holidays', 'mail'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'Time Off - PIC Pengganti',
 'summary': 'PIC Pengganti di form; email saat approve; activity log diarahkan ke PIC.',
 'version': '18.0.1.13.0',
 'website': 'https://snifx.studio',
 'post_init_hook': 'post_init_hook'}
